name = "Zero to Live"
license = "MIT"
licenselink = "https://github.com/mrlynn/hugo-zero-to-live/blob/master/LICENSE"
description = "Zero to Live is a fork of the Hero them and is a multipurpose theme with fullscreen hero images and fullwidth sections. It contains content types for a business or portfolio site."
homepage = "https://github.com/mrlynn/hugo-zero-to-live"
tags = ["responsive","minimal","clean","company","portfolio","bootstrap","zerostatic"]
features = ["services","work","fullwidth","hero images"]
min_version = 0.51

[author]
  name = "Michael Lynn"
  homepage = "https://www.zerotolive.com"